services:
  indexer:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: farcaster-indexer:latest
    container_name: farcaster-indexer
    environment: # override
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/farcaster # due to docker networking
      REDIS_URL: redis://redis:6379
      WORKER_CONCURRENCY: 10
      BACKFILL_MAX_FID: 1000
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - 3001:3001
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farcaster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  migrate:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: migrate
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/farcaster
      REDIS_URL: redis://redis:6379
    env_file: .env
    depends_on:
      - postgres
    command: ["yarn", "kysely:migrate"]
    restart: "no"

volumes:
  postgres_data:
